<a href="https://colab.research.google.com/github/Dhawaldwivedi/Data-analytics/blob/main/Da%20wd%2018/python/INbuild_functions_and_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# math function (exp , sin , log , sqrt , ceil , floor , trunc , pi , factorial)

In [22]:
import math

In [23]:
x = 36.78

In [24]:
math.exp(x)

9404832050172710.0

In [25]:
math.log(x)

3.604954219176175

In [28]:
math.sin(x)

-0.7950632429469073

In [29]:
math.sqrt(x)

6.064651680022522

In [30]:
# ceil and floor function
math.ceil(x)

37

In [31]:
math.floor(x)

36

In [32]:
math.trunc(x)

36

In [33]:
math.pi

3.141592653589793

In [34]:
math.factorial(5)

120

# Random

In [ ]:
# random , randint , sample , choice

In [35]:
import random

In [44]:
round(random.random()*100,2)

29.57

In [56]:
random.randint(1,6)

6

In [60]:
random.choice([1,3,5,4,8])

4

In [62]:
random.sample([1,3,6,8,4,87],3)

[87, 3, 1]

# String

In [ ]:
# digits , upper , lower , title , capitalize , replace , split , strip

In [74]:
s = "data science"


In [72]:
print(s.upper())
print(s.lower())
print(s.title())
print(s.capitalize())

DATA SCIENCE
data science
Data Science
Data science


In [77]:
# replace
t = s.replace('science','analytics')
t

'data analytics'

In [78]:
# split
q = s.split()
q

['data', 'science']

In [79]:
# strip
s = "      data science   "
p = s.strip()
p


'data science'

# Numpy

In [ ]:
# numpy - statistical analysis
# pandas - data manipulation
# matplolib - data visualization
# seaborn - data visualization

In [80]:
# installation
!pip install numpy

In [81]:
import numpy as np

In [82]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [84]:
type(lst)

list

In [83]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
type(arr)

numpy.ndarray

In [86]:
arr.ndim

2

In [87]:
arr.shape

(3, 3)

In [88]:
arr.size

9

In [91]:
# zeroes and ones
a = np.zeros((4,7))
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [93]:
b = np.ones((2,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [97]:
# generating random number
np.random.random()

0.6892499457266971

In [100]:
np.random.random((2,5))

array([[0.41512653, 0.37942248, 0.78132834, 0.82989351, 0.91978423],
       [0.33804831, 0.63731743, 0.98653656, 0.35524137, 0.38734183]])

In [102]:
# arange
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [103]:
np.arange(3,9,2)

array([3, 5, 7])

In [110]:
# linspace
np.linspace(3,9,24)

array([3.        , 3.26086957, 3.52173913, 3.7826087 , 4.04347826,
       4.30434783, 4.56521739, 4.82608696, 5.08695652, 5.34782609,
       5.60869565, 5.86956522, 6.13043478, 6.39130435, 6.65217391,
       6.91304348, 7.17391304, 7.43478261, 7.69565217, 7.95652174,
       8.2173913 , 8.47826087, 8.73913043, 9.        ])

In [114]:
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [115]:
# reshaping of an array
arr_reshape = np.reshape(a,(7,4))
arr_reshape

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
arr_reshape = np.reshape(a,(5,4))
arr_reshape

ValueError: cannot reshape array of size 28 into shape (5,4)

In [122]:
# flatten
print(a.flatten())


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [123]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# mathematical operations

In [128]:
arr1 = arr + 1
arr1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [129]:
arr2 = arr-3
arr2

array([[-2, -1,  0],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [130]:
arr3 = arr*3
arr3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [131]:
arr4 = arr**3
arr4

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])

In [132]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# max and sum

In [134]:
print(arr.max())

9


In [135]:
print(arr.sum())

45


In [136]:
print(arr.max(axis=1)) # row vise

[3 6 9]


In [137]:
print(arr.max(axis = 0)) # column vise

[7 8 9]


In [139]:
# sort
arr_new = np.array([[2,2,6],
                    [8,9,6],
                    [6,2,1]])
arr_new

array([[2, 2, 6],
       [8, 9, 6],
       [6, 2, 1]])

In [141]:
arr_new.sort(kind = 'merge sort')
arr_new

array([[2, 2, 6],
       [6, 8, 9],
       [1, 2, 6]])

In [142]:
arr_new.sort(axis = 0 , kind = 'merge sort')
arr_new

array([[1, 2, 6],
       [2, 2, 6],
       [6, 8, 9]])

In [143]:
# stacking and splitting
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
arr1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [148]:
arr3 = np.vstack((arr,arr2))
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [-2, -1,  0],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [149]:
arr4 = np.hstack((arr,arr2))
arr4

array([[ 1,  2,  3, -2, -1,  0],
       [ 4,  5,  6,  1,  2,  3],
       [ 7,  8,  9,  4,  5,  6]])

In [153]:
# splitting
arr5 = np.vsplit(arr3,3)
arr5

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [-2, -1,  0]]),
 array([[1, 2, 3],
        [4, 5, 6]])]

In [154]:
arr6 = np.hsplit(arr4,2)

In [155]:
arr6

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[-2, -1,  0],
        [ 1,  2,  3],
        [ 4,  5,  6]])]

In [156]:
arr+arr1

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [157]:
arr-arr1

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [158]:
arr*arr1

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

In [159]:
np.dot(arr,arr1)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])