<a href="https://colab.research.google.com/github/Dhawaldwivedi/Python-for-Data-analytics/blob/main/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# python libraries
# numpy - for mathematical calculations
# pandas - data manipulation
# seaborn - data visualization
# matplotlib - data visualization

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
arr= np.array(lst)    # making of a numpy array
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim  # for dimension of an array

2

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size # elements present in total

9

In [ ]:
# zeros function
z = np.zeros((3,5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# ones function
o = np.ones((3,4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# generate random number
np.random.random()

0.985378413578075

In [ ]:
np.random.random((2,2))

array([[0.81437863, 0.99685479],
       [0.87357781, 0.38917821]])

In [ ]:
np.random.randint(1,10000)

5614

In [ ]:
# arange function
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [ ]:
# linspace function
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
# reshaping of an array
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.reshape(z,(5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# flatten (converting an array to 1 dimension)
z.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr-1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
arr+1

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr*2

array([[ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [ ]:
arr/2

array([[1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [ ]:
arr**2

array([[  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [ ]:
# maximum element
arr

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr.max()

11

In [ ]:
arr.min()

3

In [ ]:
arr.sum()

63

In [ ]:
arr.max(axis=0)

array([ 9, 10, 11])

In [ ]:
arr.max(axis=1)

array([ 5,  8, 11])

In [ ]:
arr1 = arr.trace() # sum of diagonal elements
arr1

21

In [ ]:
# multi array
arr1 = np.array([[2,5,3],
                 [4,2,7],
                 [3,5,9]])
arr2 = np.array([[1,9,3],
                 [2,2,7],
                 [7,6,3]])

In [ ]:
arr1

array([[2, 5, 3],
       [4, 2, 7],
       [3, 5, 9]])

In [ ]:
arr2

array([[1, 9, 3],
       [2, 2, 7],
       [7, 6, 3]])

In [ ]:
arr3 = arr1+arr2
arr3

array([[ 3, 14,  6],
       [ 6,  4, 14],
       [10, 11, 12]])

In [ ]:
#indexing
arr3[:,:2]

array([[ 3, 14],
       [ 6,  4],
       [10, 11]])

In [ ]:
# sorting
arr4= np.sort(arr3,axis=1,kind='mergesort')
arr4# row vise

array([[ 3,  6, 14],
       [ 4,  6, 14],
       [10, 11, 12]])

In [ ]:
np.sort() # column vise

array([[ 3,  4,  6],
       [ 6, 11, 12],
       [10, 14, 14]])

In [ ]:
arr5 = arr4[::-1]
arr5

array([[10, 11, 12],
       [ 4,  6, 14],
       [ 3,  6, 14]])

In [ ]:
arr5 = np.array([2,5,3,4,1])
arr5

array([2, 5, 3, 4, 1])

In [ ]:
arr4= np.sort(arr5,kind='mergesort')
arr4

array([1, 2, 3, 4, 5])

In [ ]:
arr6= arr4[::-1]
arr6

array([5, 4, 3, 2, 1])

In [ ]:
np.sort(arr3, axis=1)[:, ::-1] # sorting in descending order


array([[14,  6,  3],
       [14,  6,  4],
       [12, 11, 10]])

In [ ]:
arr1

array([[2, 5, 3],
       [4, 2, 7],
       [3, 5, 9]])

In [ ]:
arr2

array([[1, 9, 3],
       [2, 2, 7],
       [7, 6, 3]])

In [ ]:
# merge array vstack function
arr3 = np.vstack((arr1,arr2))
arr3

array([[2, 5, 3],
       [4, 2, 7],
       [3, 5, 9],
       [1, 9, 3],
       [2, 2, 7],
       [7, 6, 3]])

In [ ]:
# hstack function
arr4 = np.hstack((arr1,arr2))
arr4

array([[2, 5, 3, 1, 9, 3],
       [4, 2, 7, 2, 2, 7],
       [3, 5, 9, 7, 6, 3]])

In [ ]:
# vsplit function
np.vsplit(arr3,2)


[array([[2, 5, 3],
        [4, 2, 7],
        [3, 5, 9]]),
 array([[1, 9, 3],
        [2, 2, 7],
        [7, 6, 3]])]

In [ ]:
np.hsplit(arr4,2) # hsplit function

[array([[2, 5, 3],
        [4, 2, 7],
        [3, 5, 9]]),
 array([[1, 9, 3],
        [2, 2, 7],
        [7, 6, 3]])]

In [ ]:
arr2

array([[1, 9, 3],
       [2, 2, 7],
       [7, 6, 3]])

In [ ]:
arr7= arr2[::-1]
arr7

array([[7, 6, 3],
       [2, 2, 7],
       [1, 9, 3]])